### ISSUE TITLE
Adicionar suporte ao LocalStorage

### ISSUE THREAD

**Issue by teles** [iloveblogs/guest-post#10]
A api do sheetsu até o momento não permite paginação ou buscas filtradas, ou seja, traz todos os resultados de uma vez só.

Para evitar trazer todos os resultados de uma vez toda vez que o usuário entrar na página uma estratégia possível é:
- Carregar o conteúdo quando o usuário entra pela primeira vez, adicionar o conteúdo no LocalStorage, pegar o conteúdo sempre do LocalStorage.

O que me diz @woliveiras  ?

**Comment by teles** [comment]
Outra opção válida para paginação (eu tinha esquecido) é usar o YQL: http://developer.yahoo.com/yql/console/?q=select%20*%20from%20json%20where%20url%3D%22https%3A%2F%2Fsheetsu.com%2Fapis%2Fv1.0%2F658fb938%22%20limit%2015

**Comment by woliveiras** [comment]
Acho maneiro mano! Mas teria de dar um diff do local com o que está na net. Ai teria de trazer tudo e fazer diff com o local?

**Comment by teles** [comment]
Então, para atualizar a ideia seria:
- Guardar só a data  em que o locastorage foi gerado
- Bater numa api só com a informação da última atualização
- Se estiver com data antiga no local, pede atualização....

ou utilizamos o YQL mesmo que dá para paginar bonitamente

**Comment by teles** [comment]
Dado que podemos usar o YQL, deixa quieto o LocalStorage.

**Comment by woliveiras** [comment]
Show

**Comment by teles** [comment]
@woliveiras criei uma issue para adicionar um componentezinho pra conversar com o YQL #11

**Comment by woliveiras** [comment]
Toop

Att,
William Oliveira
[image: http://]
http://woliveiras.com.br http://www.woliveiras.com.br/
http://www.woliveiras.com.br/
