### ISSUE TITLE
Criar um footer padrão para todas as páginas

### ISSUE THREAD

**Issue by teles** [iloveblogs/guest-post#25]
Definir e implementar um footer padrão para todas as páginas.
Responder:
1. Que informações são interessantes aparecerem no footer?
2. Que estilo de design deve existir no footer?

Sugestões:
1. Colocar um botão para fazer fork e para compartilhamento nas redes sociais

tem mais ideias, @woliveiras ?

**Comment by woliveiras** [comment]
Aguarde...

**Comment by woliveiras** [comment]
Mano, criei uma [estrutura parcial](https://github.com/iloveblogs/guest-post/commit/08eb882c12f414a1d233af3b9a1d6dff16e4371b) pra pensar melhor no footer. Depois vou mover ele pro template correto.

Dúvida:

Vamos usar icon fonts pra chamar os icones de redes sociais? - Acontece muito na minha internet: 

> http://blog.cloudfour.com/seriously-dont-use-icon-fonts/
