### ISSUE TITLE
Criar componente angularjs de alerta padrão

### ISSUE THREAD

**Issue by teles** [iloveblogs/guest-post#5]
Criar componente angularjs de alerta para a aplicação. 
## Requisitos
- Deve ser possível exibir mais de um alerta ao mesmo tempo na tela;
- Um alerta por padrão devem ser exibidos por 3 segundos e então sumir;
- Alerta deve conter ícone + texto de alerta + botão de fechar
- Um alerta pode ter um estilo diferente dependendo do seu contexto: amarelo para atenção, vermelho para erro, azul para informação, verde para sucesso (essas são apenas sugestões);
- O alerta deve ser fixo no topo e no centro da tela.

Aí uma issue caso você queira se divertir, @woliveiras :grinning:

**Comment by woliveiras** [comment]
Shoow

**Comment by woliveiras** [comment]
É interessante add isso aqui?

http://kouto-swiss.io/docs.html
https://jenius.github.io/rupture/

**Comment by teles** [comment]
Acho que é interessante adicionar o kouto e o rupture sim, @woliveiras.

**Comment by teles** [comment]
O estilo do alerta pode ser o mais parecido possível com o alerta do gmail.

**Comment by teles** [comment]
Deixei os alertas com esse estilo, para o MVP tá bom.
![alerts-que-aceitam-guest-post](https://cloud.githubusercontent.com/assets/762639/13765681/46a1d3f6-ea3a-11e5-91c0-459298ea1363.png)

**Comment by woliveiras** [comment]
Maravilha mano
