### ISSUE TITLE
Encontrar um estilo css para o projeto

### ISSUE THREAD

**Issue by teles** [iloveblogs/guest-post#8]
@woliveiras 

Ajuda os brother ae a encontrar um estilo css para o projeto:
- bootstrap?
- material design?
- usar o foundation e já era?
- pegar algo do jekyll themes e adaptar?

Tem alguma sugestão de framework css em stylus?

**Comment by teles** [comment]
Pensando em roubar os stylesheets daqui e modificar a paleta de cores https://github.com/codetriage/codetriage/tree/master/app/assets/stylesheets

cc @woliveiras

**Comment by woliveiras** [comment]
Os estilos do Codetriage são maneiros mano!

**Comment by teles** [comment]
Mais um estilo para roubar pro projeto http://codepen.io/ashwinsaxena/pen/wBNXPm

**Comment by teles** [comment]
Acho que já encontramos o estilo marrom menos.
Essa issue não tem critério de pronto, olha só como é difícil saber se ela deve ser fechada rs
