### ISSUE TITLE
NPM/Bower & NPM/Gulp/Grunt

### ISSUE THREAD

**Issue by woliveiras** [iloveblogs/guest-post#9]
Qual esquema vamos fazer, usar Bower/Grunt ou Gulp ou rodar tudo via NPM?

**Comment by teles** [comment]
Até agora mantive tudo no npm, inclusive o angular. Mantemos assim enquanto estivermos achando tudo no npm, já e?

**Comment by teles** [comment]
Fiz um esquema para pegar dependencias javascript do node_modules e copiar para a pasta /js/lib, o que você acha https://github.com/iloveblogs/guest-post/blob/master/tasks/copy.js ? 

Tem alguma estratégia melhor para usar dependências npm sem ter que commitar a pasta node_modules? @woliveiras

**Comment by woliveiras** [comment]
Ainda naummm :(

**Comment by teles** [comment]
@woliveiras bora continuar no gulp + npm?

**Comment by woliveiras** [comment]
Olá Jota Teles,

Conforme conversado pessoalmente, vou adicionar o Bower + Gulp.

Att,

William Oliveira
